### ISSUE TITLE
Tone mapping ruins the constant background color

### ISSUE THREAD

**Issue by LiangliangNan** [knightcrawler25/GLSL-PathTracer#61]
Hi, thanks for the great project!

In the shader code in tonemap.glsl, tonemap is applied to all pixels, which is not correct if a constant background color is desired. See the effects below:

Without tone mapping:
<img width="665" alt="Screen Shot 2021-12-29 at 12 20 30" src="https://user-images.githubusercontent.com/15526536/147658106-7b29c5e0-8a1a-4393-900c-ddd0cc7e0df4.png">

With tone mapping:
<img width="665" alt="Screen Shot 2021-12-29 at 12 21 39" src="https://user-images.githubusercontent.com/15526536/147658116-e0721aee-e2aa-48fb-88e0-f6d04ca56df3.png">

I think whether it is background can be recorded as the w component in pathTraceTexture. Maybe there are other better ideas?

**Comment by knightcrawler25** [comment]
Hi,

The background color actually acts as a constant light source (which I was using as a furnace test) so perhaps it should be named differently to avoid confusion.

I think the [standard way](https://docs.blender.org/manual/en/latest/render/cycles/render_settings/film.html#transparent) of doing this (that I know of) is to record transparency in a channel, as you mentioned, and then composite the rendered image over a white background or any other image.

Something like this:

![untitled](https://user-images.githubusercontent.com/11459803/147664502-0296bf95-435c-46e7-8745-f8aeb6b64742.png)

![glass](https://user-images.githubusercontent.com/11459803/147663828-27f3ba57-d836-4580-ab30-b0d3373b38d7.png)

Right now, the renderer doesn't track alpha/transparency and it would require some modification to get it to work.

**Comment by LiangliangNan** [comment]
Thanks for the quick reply.
Now I see. But it is indeed confusing and would be good to make it behave the same as other software.

**Comment by knightcrawler25** [comment]
I added support for background color and transparency to the dev branch. There might be some bugs and transparency doesn't work with the denoiser as of now, but you should be able to set a background color or save out an image and composite it over another image in GIMP or photoshop.

![img_113](https://user-images.githubusercontent.com/11459803/147696005-fcd01851-7644-43b8-9dc8-2801155cf3d0.png)

![Transparent](https://user-images.githubusercontent.com/11459803/147696015-186125e7-b703-4f74-a764-7a856f07d0c0.png)

**Comment by LiangliangNan** [comment]
Thanks for the efforts. Very much appreciated!
The white color works now.

Below I summary the issues I have identified in the test and in reading the code.

1) Low-reso rendering when the mouse moves. 
I found the "cornell_box.scene" is not properly rendered. It seems the low-resolution pass is not correctly rendered, or it may be due to the composition or that the previous content was not cleared. Here is a short recording: 
https://user-images.githubusercontent.com/15526536/147749593-40d0f1f4-cdf3-427b-a555-5aee230be5ed.mp4

2) Switching scenes. 
When switching to a new scene, the original contents seem not cleared. This is really weird because the renderer has been rebuilt. Here is a snapshot (which can be reproduced by firstly zooming out the cornell_box scene and then switching to cornell_box2)
![Screen Shot 2021-12-30 at 13 00 30](https://user-images.githubusercontent.com/15526536/147750365-ecdefaee-dc38-4e63-8122-708e0f02b295.png)

3) Other issues in the code. 
- in uniforms.glsl: uniform useEnvMap is never used and can be removed
- in anyhit.glsl: LIGHTS -> OPT_LIGHTS
- in pathtrace.glsl: OPENGL_NORMALMAP -> OTP_OPENGL_NORMALMAP
- in Scene.cpp: missing "delete texture;" if texture creation failed, in function "int Scene::AddTexture(const std::string& filename)";
- in Scene.cpp: "resizedTex" in function "void Scene::ProcessScene()" is allocated using "new[]" and thus should be freed using "delete []".

These things so far, hope it helps and looking forward to any update. Happy New Year!

**Comment by knightcrawler25** [comment]
Thanks a lot for pointing these out. I have pushed a commit to the repo that has the changes for 3. 

For 1 and 2 however, I'm unable to reproduce them on windows. Are you running this on Linux?

**Comment by LiangliangNan** [comment]
Oh, forgot to mention that.
I am using an apple laptop: 
  - maxOS 11.6
  - CLang 13.0.0
  - GPU: Intel(R) Iris(TM) Plus
  - OpenGL version: 4.1 INTEL-16.5.2
  - GLSL version: 4.10

To understand what goes wrong, I took snapshots for the four FBOs (every time when new contents have been written into).
https://www.dropbox.com/s/td9bfe3ijm7ou39/fbo_snapshots.zip?dl=0
I was not able to get a clue, maybe easier for you.

**Comment by knightcrawler25** [comment]
I've actually never tested the code on a mac as I don't have access to one. Unfortunately, I don't think it would be possible for me to debug this as I don't see the same issues on windows or linux. I've also tried running the code on some older hardware as well and can't replicate it.

The first issue looks rather odd, sort of like uninitialized data is being read by the shader. Do you see this issue across all scenes? Perhaps you can strip out much of the logic in pathtrace.glsl and just check if ClosestHit() is returning a proper hit

**Comment by LiangliangNan** [comment]
Now the 2nd issue has been fixed, with your latest commit and the following change:
 - in `TiledRenderer::Render()`,  after drawing into the low reso FBO, the `scene->dirty` should be changed to `false`, i.e.,              
           ` scene->instancesModified = false;` 
  becomes
           ` scene->instancesModified = false;` 
           `scene->dirty = false;` 

The first issue happens only to the "cornell_box.scene", which is really weird. I couldn't find any potential cause in the shader code.

**Comment by knightcrawler25** [comment]
Thanks, I added that change in. 

It's odd that you see an issue in that scene but not in cornell_box2.scene. The second scene uses the same objects (Difference being cbox_smallbox.obj and slight difference in light emission, material colors and path depth).

**Comment by LiangliangNan** [comment]
Indeed!

Below are 3 consecutive snapshots of the trace FBO (the lower left part of the "cornell_box. scene"). And we can see that many hits are missed:

![fbo_path_trace_012](https://user-images.githubusercontent.com/15526536/147852374-603f185d-4355-4167-a2ef-fabb42705886.jpg) ![fbo_path_trace_028](https://user-images.githubusercontent.com/15526536/147852334-460e2014-a444-4f73-bc9b-ca05dc130cd2.png) ![fbo_path_trace_044](https://user-images.githubusercontent.com/15526536/147852347-6447dcb4-ebc1-414d-93b3-291ac6ca69e1.png)

**Comment by knightcrawler25** [comment]
Is cornell_box.scene the first scene that gets loaded when you run the code? What if you switch to a different scene and then switch back to cornell_box.scene, does the issue still remain?

**Comment by LiangliangNan** [comment]
Then it is gone. But why?

**Comment by knightcrawler25** [comment]
I'm guessing it could be one of these uniforms that is not being sent to the shader the first time around and when you reload the scene things might be getting initialized properly.

https://github.com/knightcrawler25/GLSL-PathTracer/blob/a6526c8bf7964b64724b0ddea9d31a5bb1b1bffc/src/core/TiledRenderer.cpp#L520-L560

**Comment by LiangliangNan** [comment]
I've checked those uniforms and the values are the same.

Look at the result.  There are uniform regions with straight boundaries. I guess the issue might be due to the transformation of each mesh.
![Screen Shot 2022-01-01 at 16 29 36](https://user-images.githubusercontent.com/15526536/147854120-a137d7ca-726f-443c-8858-a1f7685be3cb.png)

**Comment by knightcrawler25** [comment]
Not really sure where the issue is but could you try the latest code in the dev branch and see if that fixes anything? I've refactored some of the code.

**Comment by LiangliangNan** [comment]
Thanks for the effort.  Just tried and it is still the same:
![Screen Shot 2022-01-05 at 23 41 50](https://user-images.githubusercontent.com/15526536/148300099-bdfd7338-ab0a-4cbc-b1bc-7cf893473a4d.png)

Two files that do not compile:
- Loader.cpp, line 483:    
       printf("Unable to load gltf %s\n", filename);
  should be
       printf("Unable to load gltf %s\n", filename.c_str());
-  EnvironmentMap.cpp: missing "#include <string>"

**Comment by tigrazone** [comment]
One more issue.
When I wrote in command line 
PathTracer -s c:\temp\glTF-Sample-Models\2.0\WaterBottle\glTF-Binary\WaterBottle.glb
program fails.
in Main.cpp from line 524 must be rewriten 
```
if (!sceneFile.empty())
    {
        scene = new Scene();

        GetEnvMaps();
        LoadScene(sceneFile);
    }
    else
    {
        GetSceneFiles();
        GetEnvMaps();
        LoadScene(sceneFiles[sampleSceneIdx]);
    }

```
When is no EnvMap loaded program fails also.
TiledRenderer.cpp lines 251-252 and 274-275 must be rewriten like this
`
        glUniform2f(glGetUniformLocation(shaderObject, "envMapRes"), scene->envMap == nullptr ? 0.0: (float)scene->envMap->width, scene->envMap == nullptr ? 0.0 :(float)scene->envMap->height);
        glUniform1f(glGetUniformLocation(shaderObject, "envMapTotalSum"), scene->envMap == nullptr ? 0.0 : scene->envMap->totalSum);`

**Comment by tigrazone** [comment]
I check tests from https://github.com/KhronosGroup/glTF-Sample-Models

glTF-Sample-Models\2.0\SpecularTest\ not passed. Specular parameter not changed
![image](https://user-images.githubusercontent.com/3808839/148346411-9133086b-d31f-41db-8ac4-b9f3d7ab9670.png)

glTF-Sample-Models\2.0\SpecGlossVsMetalRough\ not passed. Right bottle not texture mapped like left bottle
![image](https://user-images.githubusercontent.com/3808839/148346829-ea619d34-16d4-4d45-8dfa-0b312c729c01.png)
right result by https://github.com/SaschaWillems/Vulkan-glTF-PBR
![image](https://user-images.githubusercontent.com/3808839/148347351-517ee056-e137-4430-958a-49d85ddb85b9.png)

glTF-Sample-Models\2.0\AttenuationTest
![image](https://user-images.githubusercontent.com/3808839/148348275-74887b56-41b7-4c31-b56d-3e0a75a0ee71.png)
where is blue?
![image](https://user-images.githubusercontent.com/3808839/148348386-c09634c8-3b70-49f3-a0d9-0a6c9c79c4e2.png)

glTF-Sample-Models\2.0\TransmissionRoughnessTest
![image](https://user-images.githubusercontent.com/3808839/148348860-28944775-effd-4f9a-80d2-50004f20b328.png)

where is blue?
![image](https://user-images.githubusercontent.com/3808839/148348621-8bd471ff-ff0e-47e5-beab-a8b2a1c59fbe.png)

**Comment by knightcrawler25** [comment]
Gltf material support is not complete. Only parameters like metallic
roughness and transmission are used right now

**Comment by knightcrawler25** [comment]
@tigrazone : GLTF material support is not complete yet. Only metallic roughness workflow is used and transmissionFactor from the extensions:
https://github.com/knightcrawler25/GLSL-PathTracer/blob/ddbba9a1f2bf1c9dec0f1c2634a1af3949e5f25a/src/loaders/GLTFLoader.cpp#L245-L279

For the last screenshot, you'll have to increase number of bounces to get the blue color

**Comment by tigrazone** [comment]
Agreed with blue in scenes -  increase number of bounces helps to render blue colored boxes.
But other is not solved yet

**Comment by knightcrawler25** [comment]
@LiangliangNan : Could you also try the debug branch? It has just enough code to render cornell_box.scene and would be easier to check.

**Comment by LiangliangNan** [comment]
Now there are fewer "black" things, but still similar. See the recording below:

https://user-images.githubusercontent.com/15526536/148407642-7d879c37-f0b9-4d2e-baa0-1d764adb1bd0.mp4

**Comment by knightcrawler25** [comment]
That's good news lol. I added a couple of commits each progressively removing a feature until its down to just bvh traversal and triangle intersection. Let me know if any of the commits ends up working, that way I'll know where to look.

**Comment by LiangliangNan** [comment]
Thanks for the efforts 👍 
"Normals" is correct and "Reflect" has the problem. See below:

Disable NEE
![Disable NEE](https://user-images.githubusercontent.com/15526536/148433393-c5d6332e-adc6-4d93-97ae-078d7bfb3b0f.png)

Remove materialTex
![Remove materialTex](https://user-images.githubusercontent.com/15526536/148433453-e20e36e0-40b7-4880-a21a-f2eb62c2bb73.png)

Reflect
![Reflect](https://user-images.githubusercontent.com/15526536/148433490-4d5ce117-cfa8-4f94-9caa-de2b0e87ccc8.png)

Normals
![Normals](https://user-images.githubusercontent.com/15526536/148433550-35d5cf8a-148d-4355-a193-510c8508b700.png)

**Comment by knightcrawler25** [comment]
Normals don't look right. Was the screenshot from 9a09313dc3c8deba67cf94fe6e0a7a540b726f07?

This is what I see from that commit:

![image](https://user-images.githubusercontent.com/11459803/148439298-6a48c44f-23bf-48d8-98cc-f59174a91826.png)

**Comment by LiangliangNan** [comment]
Yes. it is from 9a09313.
The figure captions correspond to your comments

**Comment by knightcrawler25** [comment]
Do you see the same image with the last two commits where mesh transformations have been removed?

**Comment by LiangliangNan** [comment]
Here are the results from the last three commits:

hit dist:
![hit dist](https://user-images.githubusercontent.com/15526536/148597768-09822c3b-a934-4614-b4b5-16db65dadd1c.png)

remove transformation from mesh
![remove transformation from mesh](https://user-images.githubusercontent.com/15526536/148597825-f03d7938-5399-4567-9e11-adadfb184e73.png)

Remove transformation from BVH
![Remove transformation from BVH](https://user-images.githubusercontent.com/15526536/148597848-bee425d6-4d12-4f14-a482-152101972b97.png)
